{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "directus.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.KEY }}
  KEY: {{ .Values.secrets.KEY | b64enc | quote }}
  {{- else if and $existing (index $existing.data "KEY") }}
  KEY: {{ index $existing.data "KEY" | quote }}
  {{- else }}
  KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.SECRET }}
  SECRET: {{ .Values.secrets.SECRET | b64enc | quote }}
  {{- else if and $existing (index $existing.data "SECRET") }}
  SECRET: {{ index $existing.data "SECRET" | quote }}
  {{- else }}
  SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  ADMIN_EMAIL: {{ .Values.secrets.ADMIN_EMAIL | b64enc | quote }}
  {{- if .Values.secrets.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ .Values.secrets.ADMIN_PASSWORD | b64enc | quote }}
  {{- else if and $existing (index $existing.data "ADMIN_PASSWORD") }}
  ADMIN_PASSWORD: {{ index $existing.data "ADMIN_PASSWORD" | quote }}
  {{- else }}
  ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
